import type { Receipt } from "./types";

/** A ready-to-show sample so the preview is never empty on first load. */
export function genericSample(): Receipt {
  return {
    templateId: "generic",
    business: {
      name: "Brightside Goods",
      address: "120 Market Street, Springfield",
      phone: "(555) 014-2200",
    },
    meta: { receiptNo: "R-20260611-1042", date: "2026-06-11", time: "14:32", cashier: "Alex" },
    items: [
      { id: "a", qty: 1, name: "Ceramic Mug", unitPrice: 12.0 },
      { id: "b", qty: 2, name: "Drip Coffee 12oz", unitPrice: 3.75 },
      { id: "c", qty: 1, name: "Blueberry Muffin", unitPrice: 2.95 },
    ],
    currency: "USD",
    locale: "en-US",
    taxRatePct: 8.25,
    tipAmount: 0,
    paymentMethod: "card",
    cardLast4: "4242",
    footerNote: "Thank you for your purchase!",
    showTax: true,
    showTip: false,
    showSignatureLine: false,
    showBarcode: false,
    showFooter: true,
    accentColor: "#4f46e5",
    fontSize: "base",
    extras: {},
  };
}

/** Per-template presets used when a user picks a template with no existing draft. */
export const PRESETS: Record<string, () => Receipt> = {
  generic: genericSample,
  restaurant: () => ({
    ...genericSample(),
    templateId: "restaurant",
    business: { name: "The Copper Pot", address: "44 Vine Ave", phone: "(555) 220-9080" },
    items: [
      { id: "r1", qty: 2, name: "Margherita Pizza", unitPrice: 14.5 },
      { id: "r2", qty: 1, name: "Caesar Salad", unitPrice: 9.0 },
      { id: "r3", qty: 3, name: "Sparkling Water", unitPrice: 3.0 },
    ],
    taxRatePct: 7,
    showTip: true,
    tipAmount: 8,
    showSignatureLine: true,
    extras: { serverName: "Jamie", tableNo: "12" },
  }),
  thermal: () => ({
    ...genericSample(),
    templateId: "thermal",
    business: { name: "QuickMart 24", address: "9 Station Rd", phone: "555-7788" },
    fontSize: "sm",
    showBarcode: true,
    extras: { barcodeValue: "8901234567890" },
  }),
  fuel: () => ({
    ...genericSample(),
    templateId: "fuel",
    business: { name: "Summit Fuel", address: "Hwy 9 Exit 4", phone: "(555) 700-1212" },
    items: [],
    extras: {
      fuelGrade: "Unleaded 95",
      pumpNo: "6",
      unitLabel: "gal",
      unitsDispensed: 11.42,
      pricePerUnit: 3.59,
    },
  }),
  taxi: () => ({
    ...genericSample(),
    templateId: "taxi",
    business: { name: "City Cab Co.", address: "Dispatch 24/7", phone: "(555) 999-1000" },
    items: [],
    showTip: true,
    tipAmount: 3,
    extras: {
      pickup: "Airport Terminal 2",
      dropoff: "Downtown Hotel",
      distance: 14.3,
      distanceUnit: "km",
      fare: 22.5,
      surcharge: 2.0,
    },
  }),
  service: () => ({
    ...genericSample(),
    templateId: "service",
    business: { name: "Bright Studio", address: "Freelance Services", phone: "(555) 010-7788" },
    items: [
      { id: "s1", qty: 6, name: "Design hours", unitPrice: 65 },
      { id: "s2", qty: 1, name: "Stock assets", unitPrice: 40 },
    ],
    taxRatePct: 0,
    showTax: false,
    footerNote: "Thank you for your business!",
  }),
  cafe: () => ({
    ...genericSample(),
    templateId: "cafe",
    business: { name: "Bean & Co.", address: "8 Corner St", phone: "555-2210" },
    items: [
      { id: "c1", qty: 1, name: "Cappuccino", unitPrice: 3.8 },
      { id: "c2", qty: 1, name: "Croissant", unitPrice: 2.5 },
    ],
    fontSize: "sm",
    taxRatePct: 5,
  }),
  grocery: () => ({
    ...genericSample(),
    templateId: "grocery",
    business: { name: "Greenfield Market", address: "55 Orchard Rd", phone: "555-3300" },
    items: [
      { id: "g1", qty: 2, name: "Milk 1L", unitPrice: 1.6 },
      { id: "g2", qty: 1, name: "Eggs (dozen)", unitPrice: 3.2 },
      { id: "g3", qty: 3, name: "Bananas", unitPrice: 0.45 },
      { id: "g4", qty: 1, name: "Bread loaf", unitPrice: 2.1 },
    ],
    fontSize: "sm",
    showBarcode: true,
    extras: { barcodeValue: "7350120451005" },
  }),
  hotel: () => ({
    ...genericSample(),
    templateId: "hotel",
    business: { name: "Harbor View Hotel", address: "1 Marina Blvd", phone: "(555) 700-4040" },
    items: [
      { id: "h1", qty: 2, name: "Room (per night)", unitPrice: 129 },
      { id: "h2", qty: 1, name: "Resort fee", unitPrice: 25 },
    ],
    taxRatePct: 12,
  }),
  "vacation-rental": () => ({
    ...genericSample(),
    templateId: "vacation-rental",
    business: { name: "Seaside Cottage Rentals", address: "Hosted stay", phone: "(555) 612-9090" },
    items: [
      { id: "v1", qty: 3, name: "Nightly rate", unitPrice: 145 },
      { id: "v2", qty: 1, name: "Cleaning fee", unitPrice: 60 },
      { id: "v3", qty: 1, name: "Service fee", unitPrice: 48 },
    ],
    taxRatePct: 9,
    footerNote: "Thanks for staying with us!",
  }),
  bigbox: () => ({
    ...genericSample(),
    templateId: "bigbox",
    business: { name: "ValueMart Superstore", address: "200 Commerce Pkwy", phone: "555-8000" },
    items: [
      { id: "b1", qty: 1, name: "Paper towels 12pk", unitPrice: 14.97 },
      { id: "b2", qty: 2, name: "Laundry detergent", unitPrice: 11.49 },
      { id: "b3", qty: 1, name: "LED bulbs 4pk", unitPrice: 9.88 },
      { id: "b4", qty: 3, name: "Canned soup", unitPrice: 1.25 },
    ],
    fontSize: "sm",
    taxRatePct: 7.25,
    showBarcode: true,
    extras: { barcodeValue: "0490051203581" },
  }),
  pharmacy: () => ({
    ...genericSample(),
    templateId: "pharmacy",
    business: { name: "Wellness Pharmacy", address: "12 Health St", phone: "(555) 345-2211" },
    items: [
      { id: "p1", qty: 1, name: "Vitamin D3", unitPrice: 8.99 },
      { id: "p2", qty: 1, name: "Pain reliever 100ct", unitPrice: 12.49 },
      { id: "p3", qty: 2, name: "First-aid bandages", unitPrice: 3.5 },
    ],
    taxRatePct: 0,
    showTax: false,
  }),
  electronics: () => ({
    ...genericSample(),
    templateId: "electronics",
    business: { name: "TechPoint Electronics", address: "88 Circuit Ave", phone: "(555) 765-1200" },
    items: [
      { id: "e1", qty: 1, name: "Wireless earbuds", unitPrice: 79.99 },
      { id: "e2", qty: 1, name: "USB-C cable 2m", unitPrice: 12.99 },
      { id: "e3", qty: 1, name: "Phone case", unitPrice: 19.99 },
    ],
    taxRatePct: 8.5,
    paymentMethod: "card",
    cardLast4: "1187",
  }),
  marketplace: () => ({
    ...genericSample(),
    templateId: "marketplace",
    business: { name: "Maple & Co. Online", address: "Order fulfilment", phone: "support@maple.example" },
    meta: { receiptNo: "ORD-20260612-5567", date: "2026-06-12", time: "09:14" },
    items: [
      { id: "m1", qty: 1, name: "Cotton tote bag", unitPrice: 18.0 },
      { id: "m2", qty: 2, name: "Enamel pin", unitPrice: 6.5 },
      { id: "m3", qty: 1, name: "Shipping", unitPrice: 4.95 },
    ],
    taxRatePct: 6,
    footerNote: "Your order is on the way!",
  }),
  parking: () => ({
    ...genericSample(),
    templateId: "parking",
    business: { name: "Central Parking Garage", address: "Level B2", phone: "(555) 400-3030" },
    items: [],
    extras: {
      lotName: "Garage A",
      entryTime: "09:15",
      exitTime: "12:45",
      ratePerHour: 4.5,
    },
  }),
  airbnb: () => ({
    ...genericSample(),
    templateId: "airbnb",
    business: { name: "Airbnb", address: "888 Brannan St, San Francisco, CA", phone: "" },
    items: [
      { id: "ab1", qty: 3, name: "Nightly rate", unitPrice: 150 },
      { id: "ab2", qty: 1, name: "Cleaning fee", unitPrice: 60 },
      { id: "ab3", qty: 1, name: "Service fee", unitPrice: 48 },
    ],
    taxRatePct: 9.5,
    showTax: true,
    accentColor: "#FF5A5F",
    extras: {
      airbnbListingName: "Modern Loft in Downtown Seattle",
      airbnbHostName: "Alexander",
      airbnbCheckIn: "2026-06-15",
      airbnbCheckOut: "2026-06-18",
      airbnbNights: 3,
    },
  }),
  walmart: () => ({
    ...genericSample(),
    templateId: "walmart",
    business: { name: "Walmart Supercenter", address: "120 Commerce Dr, Springfield", phone: "(555) 304-2000" },
    items: [
      { id: "wm1", qty: 1, name: "HP Sprocket Printer", unitPrice: 79.99 },
      { id: "wm2", qty: 2, name: "SanDisk 128GB MicroSD", unitPrice: 19.99 },
      { id: "wm3", qty: 3, name: "Fujifilm Instax Mini Film", unitPrice: 14.50 },
    ],
    taxRatePct: 8.25,
    showBarcode: true,
    fontSize: "sm",
    extras: {
      walmartStoreNo: "1396",
      walmartTerminalNo: "04",
      walmartTransactionNo: "9821",
      walmartTcNo: "4920 8371 9028 3847 1827",
    },
  }),
  amazon: () => ({
    ...genericSample(),
    templateId: "amazon",
    business: { name: "Amazon.com", address: "Order fulfilment", phone: "" },
    items: [
      { id: "az1", qty: 1, name: "Kindle Paperwhite (16 GB)", unitPrice: 149.99 },
      { id: "az2", qty: 1, name: "Kindle Paperwhite Fabric Cover", unitPrice: 29.99 },
    ],
    taxRatePct: 6.5,
    accentColor: "#FF9900",
    extras: {
      amazonOrderNo: "114-8293740-1928374",
      amazonShipmentNo: "9876543210",
    },
  }),
  uber: () => ({
    ...genericSample(),
    templateId: "uber",
    business: { name: "Uber", address: "Dispatch 24/7", phone: "" },
    items: [],
    showTip: true,
    tipAmount: 5.0,
    taxRatePct: 8.875,
    extras: {
      pickup: "100 Broadway, New York, NY",
      dropoff: "500 5th Ave, New York, NY",
      distance: 3.8,
      distanceUnit: "mi",
      fare: 18.5,
      surcharge: 2.5,
      uberDriverName: "David",
      uberVehicleInfo: "Toyota Camry (UberX)",
      uberTripDuration: "18 min",
    },
  }),
  starbucks: () => ({
    ...genericSample(),
    templateId: "starbucks",
    business: { name: "Starbucks Coffee", address: "450 Lexington Ave, New York, NY", phone: "(212) 555-9018" },
    items: [
      { id: "sb1", qty: 1, name: "Grande Caramel Macchiato", unitPrice: 5.45 },
      { id: "sb2", qty: 1, name: "Butter Croissant", unitPrice: 3.75 },
    ],
    taxRatePct: 8.875,
    fontSize: "sm",
    accentColor: "#00704A",
    extras: {
      starbucksCheckNo: "19385",
      starbucksStarsEarned: "18",
    },
  }),
  nike: () => ({
    ...genericSample(),
    templateId: "nike",
    business: { name: "Nike Store", address: "1 Bowerman Drive", phone: "1-800-806-6453" },
    items: [
      { id: "nk1", qty: 1, name: "Air Force 1 '07", unitPrice: 115 },
      { id: "nk2", qty: 2, name: "Everyday Plus Cushioned Socks", unitPrice: 18 },
    ],
    taxRatePct: 8.5,
    accentColor: "#111111",
    extras: {
      nikeOrderNo: "C0100938472",
    },
  }),
  adidas: () => ({
    ...genericSample(),
    templateId: "adidas",
    business: { name: "Adidas", address: "5055 N Greeley Ave", phone: "1-800-982-9337" },
    items: [
      { id: "ad1", qty: 1, name: "Samba OG Shoes", unitPrice: 100 },
      { id: "ad2", qty: 1, name: "Trefoil Tee", unitPrice: 30 },
    ],
    taxRatePct: 8.5,
    accentColor: "#000000",
    extras: {
      adidasOrderNo: "ADU10984729",
    },
  }),
  apple: () => ({
    ...genericSample(),
    templateId: "apple",
    business: { name: "Apple Store", address: "One Apple Park Way", phone: "1-800-MY-APPLE" },
    items: [
      { id: "ap1", qty: 1, name: "AirPods Pro (2nd gen)", unitPrice: 249 },
      { id: "ap2", qty: 1, name: "AppleCare+ for AirPods", unitPrice: 29 },
    ],
    taxRatePct: 9.0,
    accentColor: "#000000",
    extras: {
      appleOrderNo: "W983472910",
    },
  }),
  jordan: () => ({
    ...genericSample(),
    templateId: "jordan",
    business: { name: "Jordan Store", address: "State Street, Chicago", phone: "1-800-806-6453" },
    items: [
      { id: "jd1", qty: 1, name: "Air Jordan 1 Retro High", unitPrice: 180 },
    ],
    taxRatePct: 10.25,
    accentColor: "#E32636",
    extras: {
      jordanOrderNo: "JD9983472",
    },
  }),
};

export function presetFor(templateId: string): Receipt {
  const make = PRESETS[templateId] ?? genericSample;
  return make();
}
