import { z } from "zod";

export const lineItemSchema = z.object({
  id: z.string(),
  qty: z.coerce.number().min(0, "Qty ≥ 0"),
  name: z.string().max(120, "Too long"),
  unitPrice: z.coerce.number().min(0, "Price ≥ 0"),
});

export const receiptSchema = z.object({
  templateId: z.string(),
  business: z.object({
    name: z.string().max(120),
    address: z.string().max(240),
    phone: z.string().max(60),
    logoDataUrl: z.string().optional(),
  }),
  meta: z.object({
    receiptNo: z.string().max(60),
    date: z.string(),
    time: z.string(),
    cashier: z.string().max(60).optional(),
  }),
  items: z.array(lineItemSchema),
  currency: z.string().length(3),
  locale: z.string(),
  taxRatePct: z.coerce.number().min(0).max(100),
  tipAmount: z.coerce.number().min(0).optional(),
  paymentMethod: z.enum(["cash", "card", "other"]),
  cardLast4: z.string().max(4).optional(),
  footerNote: z.string().max(240).optional(),
  showTax: z.boolean(),
  showTip: z.boolean(),
  showSignatureLine: z.boolean().optional(),
  showBarcode: z.boolean().optional(),
  showFooter: z.boolean(),
  accentColor: z.string(),
  fontSize: z.enum(["sm", "base", "lg"]),
  extras: z.object({
    serverName: z.string().optional(),
    tableNo: z.string().optional(),
    fuelGrade: z.string().optional(),
    pumpNo: z.string().optional(),
    unitLabel: z.string().optional(),
    unitsDispensed: z.coerce.number().min(0).optional(),
    pricePerUnit: z.coerce.number().min(0).optional(),
    pickup: z.string().optional(),
    dropoff: z.string().optional(),
    distance: z.coerce.number().min(0).optional(),
    distanceUnit: z.string().optional(),
    fare: z.coerce.number().min(0).optional(),
    surcharge: z.coerce.number().min(0).optional(),
    lotName: z.string().optional(),
    entryTime: z.string().optional(),
    exitTime: z.string().optional(),
    ratePerHour: z.coerce.number().min(0).optional(),
    barcodeValue: z.string().optional(),
    airbnbListingName: z.string().optional(),
    airbnbHostName: z.string().optional(),
    airbnbCheckIn: z.string().optional(),
    airbnbCheckOut: z.string().optional(),
    airbnbNights: z.coerce.number().min(0).optional(),
    walmartStoreNo: z.string().optional(),
    walmartTerminalNo: z.string().optional(),
    walmartTransactionNo: z.string().optional(),
    walmartTcNo: z.string().optional(),
    amazonOrderNo: z.string().optional(),
    amazonShipmentNo: z.string().optional(),
    uberDriverName: z.string().optional(),
    uberVehicleInfo: z.string().optional(),
    uberTripDuration: z.string().optional(),
    starbucksStarsEarned: z.string().optional(),
    starbucksCheckNo: z.string().optional(),
    nikeOrderNo: z.string().optional(),
    adidasOrderNo: z.string().optional(),
    appleOrderNo: z.string().optional(),
    jordanOrderNo: z.string().optional(),
  }),
});

export type ReceiptForm = z.infer<typeof receiptSchema>;
